#
# 86Box		A hypervisor and IBM PC system emulator that specializes in
#		running old operating systems and software designed for IBM
#		PC systems and compatibles from 1981 through fairly recent
#		system designs based on the PCI bus.
#
#		This file is part of the 86Box Probing Tools distribution.
#
#		Makefile for compiling C-based tools with Watcom.
#
#
#
# Authors:	RichardG, <richardg867@gmail.com>
#
#		Copyright 2021 RichardG.
#

SYSTEM	= PMODEW
OBJS	= pcireg.obj lh5_extract.obj clib_pci.obj clib_std.obj clib_sys.obj clib_term.obj
DEST	= PCIREG.EXE

!include ../clib/watcom.mk
